Update config

diff --git a/config b/config
--- a/config
+++ b/config
@@ -1,157 +1,78 @@
-[aceuser@60464662ca24 opt]$ rpm -qa
-crypto-policies-20200713-1.git51d1222.el8.noarch
-redhat-release-8.3-1.0.el8.x86_64
-filesystem-3.8-3.el8.x86_64
-publicsuffix-list-dafsa-20180723-1.el8.noarch
-pcre2-10.32-2.el8.x86_64
-ncurses-libs-6.1-7.20180224.el8.x86_64
-glibc-common-2.28-127.el8.x86_64
-bash-4.4.19-12.el8.x86_64
-zlib-1.2.11-16.el8_2.x86_64
-xz-libs-5.2.4-3.el8.x86_64
-bzip2-libs-1.0.6-26.el8.x86_64
-libcap-2.26-4.el8.x86_64
-libffi-3.1-22.el8.x86_64
-libunistring-0.9.9-3.el8.x86_64
-libxml2-2.9.7-8.el8.x86_64
-readline-7.0-10.el8.x86_64
-libgcrypt-1.8.5-4.el8.x86_64
-sqlite-libs-3.26.0-11.el8.x86_64
-libacl-2.2.53-1.el8.x86_64
-sed-4.5-2.el8.x86_64
-libtasn1-4.13-3.el8.x86_64
-libzstd-1.4.4-1.el8.x86_64
-lz4-libs-1.8.3-2.el8.x86_64
-grep-3.1-6.el8.x86_64
-libmount-2.32.1-24.el8.x86_64
-libusbx-1.0.23-4.el8.x86_64
-p11-kit-trust-0.23.14-5.el8_0.x86_64
-openssl-libs-1.1.1g-12.el8_3.x86_64
-libdb-utils-5.3.28-39.el8.x86_64
-libpsl-0.20.2-6.el8.x86_64
-nettle-3.4.1-2.el8.x86_64
-glib2-2.56.4-8.el8.x86_64
-librhsm-0.0.3-3.el8.x86_64
-libpeas-1.22.0-6.el8.x86_64
-file-libs-5.33-16.el8.x86_64
-expat-2.2.5-4.el8.x86_64
-json-c-0.13.1-0.2.el8.x86_64
-libcap-ng-0.7.9-5.el8.x86_64
-libnghttp2-1.33.0-3.el8_2.1.x86_64
-gawk-4.2.1-1.el8.x86_64
-libverto-0.3.0-5.el8.x86_64
-libxcrypt-4.1.1-4.el8.x86_64
-openldap-2.4.46-15.el8.x86_64
-npth-1.5-4.el8.x86_64
-gpgme-1.13.1-3.el8.x86_64
-libssh-0.9.4-2.el8.x86_64
-curl-7.61.1-14.el8_3.1.x86_64
-rpm-libs-4.14.3-4.el8.x86_64
-libsolv-0.7.11-1.el8.x86_64
-libdnf-0.48.0-5.el8.x86_64
-langpacks-en-1.0-12.el8.noarch
-gpg-pubkey-fd431d51-4ae0493b
-tzdata-2020f-1.el8.noarch
-libnsl2-1.2.0-2.20180605git4a062cf.el8.x86_64
-python3-setuptools-wheel-39.2.0-6.el8.noarch
-gdbm-1.18-1.el8.x86_64
-platform-python-3.6.8-31.el8.x86_64
-platform-python-pip-9.0.3-18.el8.noarch
-python3-pip-9.0.3-18.el8.noarch
-libsemanage-2.9-3.el8.x86_64
-libutempter-1.1.6-14.el8.x86_64
-gzip-1.9-9.el8.x86_64
-cracklib-dicts-2.9.6-15.el8.x86_64
-pam-1.3.1-11.el8.x86_64
-openssl-1.1.1g-12.el8_3.x86_64
-unzip-6.0-43.el8.x86_64
-libgcc-8.3.1-5.1.el8.x86_64
-setup-2.12.2-6.el8.noarch
-basesystem-11-5.el8.noarch
-ncurses-base-6.1-7.20180224.el8.noarch
-libselinux-2.9-4.el8_3.x86_64
-glibc-minimal-langpack-2.28-127.el8.x86_64
-glibc-2.28-127.el8.x86_64
-libsepol-2.9-1.el8.x86_64
-libgpg-error-1.31-1.el8.x86_64
-info-6.5-6.el8.x86_64
-gmp-6.1.2-10.el8.x86_64
-libcom_err-1.45.6-1.el8.x86_64
-p11-kit-0.23.14-5.el8_0.x86_64
-libidn2-2.2.0-1.el8.x86_64
-popt-1.16-14.el8.x86_64
-libassuan-2.5.1-3.el8.x86_64
-elfutils-libelf-0.180-1.el8.x86_64
-libattr-2.4.48-3.el8.x86_64
-coreutils-single-8.30-8.el8.x86_64
-libsmartcols-2.32.1-24.el8.x86_64
-libuuid-2.32.1-24.el8.x86_64
-lua-libs-5.3.4-11.el8.x86_64
-pcre-8.42-4.el8.x86_64
-libblkid-2.32.1-24.el8.x86_64
-systemd-libs-239-41.el8_3.1.x86_64
-chkconfig-1.13-2.el8.x86_64
-ca-certificates-2020.2.41-80.0.el8_2.noarch
-libdb-5.3.28-39.el8.x86_64
-libarchive-3.3.2-9.el8.x86_64
-mpfr-3.1.6-1.el8.x86_64
-gnutls-3.6.14-7.el8_3.x86_64
-json-glib-1.4.4-1.el8.x86_64
-gobject-introspection-1.56.1-1.el8.x86_64
-libksba-1.3.5-7.el8.x86_64
-brotli-1.0.6-2.el8.x86_64
-libmetalink-0.1.3-7.el8.x86_64
-keyutils-libs-1.5.10-6.el8.x86_64
-audit-libs-3.0-0.17.20191104git1c2f876.el8.x86_64
-libsigsegv-2.11-5.el8.x86_64
-libstdc++-8.3.1-5.1.el8.x86_64
-krb5-libs-1.18.2-5.el8.x86_64
-cyrus-sasl-lib-2.1.27-5.el8.x86_64
-libyaml-0.1.7-5.el8.x86_64
-gnupg2-2.2.20-2.el8.x86_64
-libssh-config-0.9.4-2.el8.noarch
-libcurl-7.61.1-14.el8_3.1.x86_64
-rpm-4.14.3-4.el8.x86_64
-libmodulemd-2.9.4-2.el8.x86_64
-librepo-1.12.0-2.el8.x86_64
-microdnf-3.4.0-1.el8.x86_64
-rootfiles-8.1-22.el8.noarch
-gpg-pubkey-d4082792-5b32db75
-libtirpc-1.1.4-4.el8.x86_64
-python3-pip-wheel-9.0.3-18.el8.noarch
-gdbm-libs-1.18-1.el8.x86_64
-python3-libs-3.6.8-31.el8.x86_64
-platform-python-setuptools-39.2.0-6.el8.noarch
-python3-setuptools-39.2.0-6.el8.noarch
-python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64
-shadow-utils-4.6-11.el8.x86_64
-libfdisk-2.32.1-24.el8.x86_64
-cracklib-2.9.6-15.el8.x86_64
-libpwquality-1.4.0-9.el8.x86_64
-util-linux-2.32.1-24.el8.x86_64
-findutils-4.6.0-20.el8.x86_64
-[aceuser@60464662ca24 opt]$
+# ================= CACHE STAGE =================
+- stage: Cache
+  displayName: CACHE
+  pool:
+    name: TFS-RH-1
+  dependsOn:
+    - Validation_Stage
+    - Build
+  condition: |
+    and(
+      succeeded('Validation_Stage'),
+      eq(dependencies.Validation_Stage.outputs['Validation_Job.val_task.CacheFlag'], 'true'),
+      or(
+        eq(dependencies.Validation_Stage.outputs['Validation_Job.val_task.DeployFlag'], 'false'),
+        succeeded('Build')
+      ),
+      ne(variables['Build.SourceBranchName'], 'main')
+    )
 
-[aceuser@60464662ca24 ace-11]$ ls -lrth
-total 56K
-drwxrwxr-x  2 root root 4.0K Oct  4  2019 extensions
-drwxrwxr-x  2 root root 4.0K Oct  4  2019 swidtag
-drwxrwxr-x 15 root root 4.0K Oct  4  2019 readmes
-drwxr-xr-x  5 root root 4.0K Oct  4  2019 ie02
--rwxr-xr-x  1 root root  27K Oct  4  2019 ace
-drwxrwxr-x 35 root root 4.0K Oct  4  2019 server
-drwxrwxr-x  2 root root 4.0K Jan  7  2021 license
-drwxrwxr-x 11 root root 4.0K Jan  7  2021 common
-[aceuser@60464662ca24 ace-11]$ du -sch *
-28K     ace
-383M    common
-4.0K    extensions
-3.3M    ie02
-4.3M    license
-204K    readmes
-956M    server
-36K     swidtag
-1.4G    total
-[aceuser@60464662ca24 ace-11]$
+  jobs:
+    - job: Cache_Job
+      displayName: CACHE UPDATE
+      workspace:
+        clean: all
+
+      steps:
+
+        - download: current
+          artifact: drop
+
+        - task: CmdLine@2
+          displayName: Update cache in Database
+          env:
+            BRANCH: $(Build.SourceBranchName)
+          inputs:
+            workingDirectory: $(Pipeline.Workspace)/drop/
+            script: |
+              source ~/.bashrc
+              set -e
+              if [ ! -f config.yml ]; then
+                echo "config.yml file was not found !!"
+                exit 1
+              fi
+
+              yq ".Cache[].Query" config.yml | while IFS= read -r SQL; do
+                echo "Executing SQL: $SQL"
+                OUTPUT=$(echo "$SQL" | isql -v "$BRANCH" "$DB_USER" "$DB_PASS" -b 2>&1)
+                STATUS=$?
+                echo "$OUTPUT"
+                if [[ $STATUS -eq 0 ]] && echo "$OUTPUT" | grep -qi "SQLRowCount"; then
+                  echo "SUCCESS: Query executed"
+                else
+                  echo "FAILED: Query did not execute"
+                  exit 1
+                fi
+              done
 
 
+
+
+
+Update cache in Database
+
+View raw log
+Starting: Update cache in Database
+==============================================================================
+Task         : Command line
+Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
+Version      : 2.231.0
+Author       : Microsoft Corporation
+Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
+==============================================================================
+Generating script.
+========================== Starting Command Output ===========================
+/usr/bin/bash --noprofile --norc /home/azagent/_work/_temp/7a7cc6a5-e1fa-4029-91c1-4d5744455972.sh
+Executing SQL: INSERT into EISSIT.cache_details (FIELD_NAME, FIELD_VALUE, REQUEST_ACTION, PROCESSING_ACTION, RESPONSE_ACTION, SOURCE_ID, BACKEND_TYPE, BACKEND_SUB_TYPE, TRAN_CODE, SERVICE_NAME,CREATION_TIME) VALUES('IT_JVP_THINK360_SA_DOWNLOAD_REPORT_CCSID_TEST11','ST|Y2_test9','SOURCE_ID','SOURCE ID CONFIGURATION','NULL','MULTIPLE','THINK360','SA_DOWNLOAD_REPORT','IT_JVP','thirdPartyAAMAZE_sys',TRUNC(SYSDATE))
+##[error]Bash exited with code '139'.
+Finishing: Update cache in Database
