Update scrip

diff --git a/scrip b/scrip
--- a/scrip
+++ b/scrip
@@ -1,33 +1,277 @@
-[eisuser@eisuatsftp01 Denny]$ podman pod ps
-POD ID        NAME                STATUS      CREATED         INFRA ID      # OF CONTAINERS
-767ec6584fc9  app-deployment-pod  Running     12 seconds ago  5977c8e9a402  2
-[eisuser@eisuatsftp01 Denny]$
-[eisuser@eisuatsftp01 Denny]$ podman ps
-CONTAINER ID  IMAGE                                    COMMAND     CREATED         STATUS         PORTS                    NAMES
-41a0b527a4c6  localhost/rhel:9.6                       /bin/bash   2 days ago      Up 2 days                               confident_euler
-5977c8e9a402  localhost/podman-pause:5.4.0-1739375653              21 seconds ago  Up 22 seconds  0.0.0.0:50032->8080/tcp  767ec6584fc9-infra
-19fa7ea41f7e  localhost/app:v1.1                                   21 seconds ago  Up 21 seconds  0.0.0.0:50032->8080/tcp  app-deployment-pod-application
-[eisuser@eisuatsftp01 Denny]$ cat app-deplyoyment.yaml
-apiVersion: v1
-kind: Deployment
-metadata:
-  name: app-deployment
-  labels:
-    app: application
-spec:
-  selector:
-    matchLabels:
-      app: application
-  template:
-    metadata:
-      labels:
-        app: application
-    spec:
-      containers:
-      - name: application
-        image: app:v1.1
-        ports:
-        - containerPort: 8080
-          hostPort: 50032
 
-[eisuser@eisuatsftp01 Denny]$
+
+trigger:
+  branches:
+    include:
+    - refs/heads/SIT
+    - refs/heads/UAT
+    - refs/heads/DEV
+    - refs/heads/PRE-PROD
+    - refs/heads/main
+
+
+
+stages:
+# ============== Validation and Initilization ============
+- stage: Validation_Stage
+  displayName: Validation and Intialization
+  pool:
+    name: TFS-RH-1
+  jobs:
+    - job: Validation_Job
+      displayName: Validation
+      steps:
+
+        - checkout: self
+
+        - task: CmdLine@2
+          name: val_task
+          env:
+            BRANCH: $(Build.SourceBranchName)
+          displayName: Validating repository
+          inputs:
+            script: |
+              set -e
+
+              config_path=$(Build.SourcesDirectory)/Config/config.yml
+              if [ -z "$config_path" ] || [ ! -f "$config_path" ]; then
+                echo "ERROR: config.yml not found"
+                exit 1
+              fi
+
+              REQUIRED_FIELDS=(
+                ApplicationName
+                IntegrationNode
+                IntegrationServer
+              )
+              for field in "${REQUIRED_FIELDS[@]}"; do
+                value=$(yq e ".$BRANCH.$field // \"\"" "$config_path" | tr -d '[:space:]')
+                if [ -z "$value" ]; then
+                  echo " ERROR: $field is missing or empty for branch $BRANCH in config.yml"
+                  exit 1
+                fi
+              done
+
+              DEPLOY=$(yq e ".$BRANCH.Deploy" "$config_path" | tr -d '[:space:]')
+              CACHE_PRESENT=$(yq e ".$BRANCH.Cache // [] | length > 0" "$config_path" | tr -d '[:space:]')
+              echo "CACHE: $CACHE_PRESENT DEPLOY: $DEPLOY"
+              if [ "$DEPLOY" = false ] || [ "$DEPLOY" = "false" ]; then
+                DEPLOY="false"
+              else
+                DEPLOY="true"
+              fi
+              if [ "$CACHE_PRESENT" = true ] || [ "$CACHE_PRESENT" = "true" ]; then
+                CACHE_PRESENT="true"
+              else
+                CACHE_PRESENT="false"
+              fi
+
+              if [ "$DEPLOY" != true ] && [ "$DEPLOY" != false ]; then
+                echo "Invalid Deploy flag in config.yml"
+                exit 1
+              fi
+
+              echo "##vso[task.setvariable variable=DeployFlag;isOutput=true]$DEPLOY"
+              echo "##vso[task.setvariable variable=CacheFlag;isOutput=true]$CACHE_PRESENT"
+
+
+        - task: PublishBuildArtifacts@1
+          condition: eq(variables['val_task.DeployFlag'], false)
+          inputs:
+            PathtoPublish: $(build.sourcesDirectory)/Config/
+            ArtifactName: drop
+                   
+
+# ================= BUILD STAGE =================
+- stage: Build
+  displayName: Build Stage
+  dependsOn: Validation_Stage
+  pool:
+    name: TFS-RH-1
+  condition: |
+    and(
+        succeeded('Validation_Stage'),
+        eq(
+          dependencies.Validation_Stage.outputs['Validation_Job.val_task.DeployFlag'],
+          'true'
+        )
+      )
+  jobs:
+    - job: Build_Job
+      displayName: Agent Build job 
+      steps:
+
+        - checkout: self
+
+        - task: CmdLine@2
+          displayName: Building Bar file
+          env:
+            BRANCH: $(Build.SourceBranchName)
+          inputs:
+            script: |
+              set -e
+              . /opt/IBM/ace/server/bin/mqsiprofile
+              
+              config_path=$(Build.SourcesDirectory)/Config/config.yml
+              applicationName=$(yq e ".$BRANCH.ApplicationName" "$config_path")
+              override_path=$(find . -iname "override.properties")
+
+              if [ -f "$override_path" ]; then
+                ibmint package --input-path $(Build.SourcesDirectory) \
+                               --output-bar-file $(Build.BinariesDirectory)/$applicationName.bar \
+                               --java-version 8 \
+                               --overrides-file "$override_path"
+              else
+                ibmint package --input-path $(Build.SourcesDirectory) \
+                               --output-bar-file $(Build.BinariesDirectory)/$applicationName.bar \
+                               --java-version 8
+              fi
+
+              yq ".$BRANCH.Overrides | to_entries[] | \"\(.key) \(.value)\"" "$config_path" | while read key value;
+              do [ -z "$key" ] && continue;
+              mqsiapplybaroverride  -b $(Build.BinariesDirectory)/"$applicationName".bar -k "$applicationName" -m "gen.$applicationName#$key=$value";
+              done
+
+              cp "$config_path" $(Build.BinariesDirectory)
+        
+        - task: CopyFiles@2
+          inputs:
+            SourceFolder: $(Build.BinariesDirectory)
+            TargetFolder: $(Build.ArtifactStagingDirectory)
+            OverWrite: true
+
+        - task: PublishBuildArtifacts@1
+          inputs:
+            PathtoPublish: $(Build.ArtifactStagingDirectory)
+            ArtifactName: drop
+
+
+# ================= RELEASE STAGE =================
+- stage: Release
+  displayName: Deploy Stage
+  pool:
+    name: TFS-RH-1
+  dependsOn: Build
+  condition: |
+    and(
+      succeeded('Build'),
+      eq(
+          dependencies.Validation_Stage.outputs['Validation_Job.val_task.DeployFlag'],
+          'true'
+        )
+    )
+  jobs:
+    - deployment: DeployApp
+      displayName: Deployment Job
+      environment: $(Build.SourceBranchName)
+      strategy:
+        runOnce:
+          deploy:
+            steps:
+
+              - download: current
+                artifact: drop
+
+              - task: CmdLine@2
+                displayName: Deploying Bar File
+                env:
+                  BRANCH: $(Build.SourceBranchName)
+                inputs:
+                  workingDirectory: $(Pipeline.Workspace)/drop
+                  script: |
+                    set -e
+                    . /opt/IBM/ace/server/bin/mqsiprofile
+
+                    IntegrationNode=$(yq e ".$BRANCH.IntegrationNode" config.yml)
+                    ApplicationName=$(yq e ".$BRANCH.ApplicationName" config.yml)
+                    IntegrationServer=$(yq e ".$BRANCH.IntegrationServer" config.yml)
+
+                    for broker_file in /home/devops/broker/$BRANCH/$IntegrationNode*; do
+                      cat "$broker_file" |grep host| awk -F"\"" '{print "HOST: " $4 " , " "IntegrationNode: " $6}'
+                      ibmint deploy \
+                        --input-bar-file "$ApplicationName.bar" \
+                        --integration-node-file "$broker_file" \
+                        --output-server "$IntegrationServer"
+                    done
+
+# ================= CACHE STAGE =================
+- stage: Cache
+  displayName: CACHE
+  pool:
+    name: TFS-RH-1
+  dependsOn: 
+    - Validation_Stage
+    - Build
+  condition: |
+    and(
+      succeeded('Validation_Stage'),
+      eq(
+          dependencies.Validation_Stage.outputs['Validation_Job.val_task.CacheFlag'],
+          'true'
+        ),
+      or(
+        eq(
+          dependencies.Validation_Stage.outputs['Validation_Job.val_task.DeployFlag'],
+          'false'
+        ),
+        succeeded('Build')
+      )
+    )
+  jobs:
+    - job: Cache_Job
+      displayName: CACHE UPDATE
+      steps:
+        
+        - download: current
+          artifact: drop
+
+        - task: CmdLine@2
+          displayName: Update cache in Database
+          env:
+            BRANCH: $(Build.SourceBranchName)
+          inputs:
+            workingDirectory: $(Pipeline.Workspace)/drop/
+            script: |
+              source ~/.bashrc
+              set -e
+              if [ ! -f config.yml ];
+              then echo "config.yml file was not found !!"; exit 1;
+              fi
+              yq ".$BRANCH.Cache[].Query" config.yml | while  IFS= read -r SQL;
+              do echo "---------------------------------------------------------";
+              echo "Executing SQL Cache Query";
+              echo "$SQL";
+              echo "---------------------------------------------------------";
+              OUTPUT=$(echo "$SQL" | isql "$BRANCH" "$DB_USER" "$DB_PASS" 2>&1);
+              STATUS=$?;
+              if [[ $STATUS -eq 0 ]] && echo "$OUTPUT" | grep -qi "SQLRowCount";
+              then echo "SUCCESS: Query executed";
+              else echo "FAILED: Query did not execute"; exit 1;
+              fi;
+              echo " ";
+              done
+
+        - task: CmdLine@2
+          displayName: Update Cache in Server
+          env:
+            BRANCH: $(Build.SourceBranchName)
+          inputs:
+            workingDirectory: $(Pipeline.Workspace)/drop/
+            script: |
+              set -e
+
+              IntegrationNode=$(yq ".$BRANCH.IntegrationNode" config.yml)
+              for broker_file in /home/devops/broker/$BRANCH/$IntegrationNode*; do
+                host=$(cat "$broker_file" | grep host | cut -d"\"" -f4)
+                if yq -e ".$BRANCH.Cache" config.yml >/dev/null 2>&1; then
+                  response=$(curl -s -k -X POST http://"$host":8002/cache/v1/loadCache \
+                  -H "Content-Type: application/json" \
+                  -d "$(yq -o=json ".$BRANCH.Cache | map({\"FIELD_NAME\": .FIELD_NAME, \"FIELD_VALUE\": .FIELD_VALUE})" config.yml)")
+                  if [[ "$response" != *'"RESPONSE":"success"'* ]]; then
+                    echo "Cache load failed: $response"
+                    exit 1
+                  fi
+                  echo "Cache load successful on $host"
+                  echo "$(yq -o=json ".$BRANCH.Cache | map({\"FIELD_NAME\": .FIELD_NAME, \"FIELD_VALUE\": .FIELD_VALUE})" config.yml)"
+                fi
+              done
